collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8835126
  brandStrength: 0.4713262
  lightness: 0.9802867
  brandColors:
    - '#151618'
    - '#BDD05C'
    - '#FFFFFF'
    - '#26456E'
    - '#4A79AC'
  rhythmicContrast: 0.8440861
typography_spectrum: 0.4086021
layout_spectrum: 0.2329749
name: TRITTOINTERNATIONAL
