layout_spectrum: 0.2329749
color:
  saturation: 0.0734767
  lightness: 0.4677419
  brandStrength: 0.1179429
  rhythmicContrast: 0
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.4086021
name: TRITTOINTERNATIONAL
